;;; STEGH.LSP v7.0 -- ΜΕΘΟΔΟΣ ΔΙΑΣΠΑΣΗΣ ΣΕ ΟΡΘΟΓΩΝΙΑ
;;; 1. Διάσπαση κάτοψης στις εσοχές -> απλά ορθογώνια
;;; 2. Καθε ορθογωνιο: 4 μαχιες 45 μοιρων + κορφιας στη μεση
;;; 3. Φιλτραρισμα τεχνητων γραμμων
;;; Εντολή: STEGH | HEXIS -- BRB DEVELOPMENT

(setq *st-PIT* 35.0 *st-PMODE* "PCT" *st-OVH* 0.50 *st-TYP* "ISO")

(defun st-layer (nm col)
  (if (null (tblsearch "LAYER" nm))
    (entmake (list (cons 0 "LAYER") (cons 100 "AcDbSymbolTableRecord")
                   (cons 100 "AcDbLayerTableRecord") (cons 2 nm)
                   (cons 70 0) (cons 62 col) (cons 6 "Continuous")))))

(defun st-line (p1 p2 lyr)
  (entmake (list (cons 0 "LINE") (cons 100 "AcDbEntity") (cons 8 lyr)
                 (cons 10 (list (car p1) (cadr p1) 0.0))
                 (cons 11 (list (car p2) (cadr p2) 0.0)))))

(defun st-pline (pts lyr / el)
  (setq el (list (cons 0 "LWPOLYLINE") (cons 100 "AcDbEntity") (cons 8 lyr)
                 (cons 100 "AcDbPolyline") (cons 90 (length pts)) (cons 70 1)))
  (foreach p pts (setq el (append el (list (cons 10 (list (car p) (cadr p)))))))
  (entmake el))

(defun st-txt (p h str lyr)
  (entmake (list (cons 0 "TEXT") (cons 100 "AcDbEntity") (cons 8 lyr)
                 (cons 10 (list (car p) (cadr p) 0.0)) (cons 40 h)
                 (cons 1 str) (cons 72 1)
                 (cons 11 (list (car p) (cadr p) 0.0)))))

(defun st-getpts (ent / ed pts pr)
  (setq ed (entget ent) pts (list))
  (foreach pr ed (if (= (car pr) 10)
    (setq pts (append pts (list (list (cadr pr) (caddr pr)))))))
  (if (and (> (length pts) 1) (< (distance (car pts) (last pts)) 1e-6))
    (setq pts (reverse (cdr (reverse pts))))) pts)

(defun st-area2 (pts / n i p q a)
  (setq n (length pts) a 0.0 i 0)
  (while (< i n) (setq p (nth i pts) q (nth (rem (1+ i) n) pts))
    (setq a (+ a (- (* (car p) (cadr q)) (* (car q) (cadr p))))) (setq i (1+ i))) a)

(defun st-mid (a b) (list (/ (+ (car a) (car b)) 2.0) (/ (+ (cadr a) (cadr b)) 2.0)))

; υπολίστα από index a έως index b κυκλικά
(defun st-sub (pts a b / n out k cnt)
  (setq n (length pts) out (list) k a cnt 0)
  (while (and (< cnt (1+ n)))
    (setq out (append out (list (nth k pts))))
    (if (= k b) (setq cnt (+ n 5)) (progn (setq k (rem (1+ k) n)) (setq cnt (1+ cnt)))))
  out)

(defun st-clean (pts / out n i a c b cr la lb res)
  (setq out (list))
  (foreach p pts
    (if (or (null out) (> (distance p (last out)) 1e-6))
      (setq out (append out (list p)))))
  (if (and (> (length out) 1) (< (distance (car out) (last out)) 1e-6))
    (setq out (reverse (cdr (reverse out)))))
  (setq n (length out) res (list) i 0)
  (while (< i n)
    (setq a (nth (rem (+ i (1- n)) n) out) c (nth i out) b (nth (rem (1+ i) n) out))
    (setq cr (- (* (- (car c) (car a)) (- (cadr b) (cadr c)))
               (* (- (cadr c) (cadr a)) (- (car b) (car c)))))
    (setq la (distance a c) lb (distance c b))
    (if (and (> la 1e-9) (> lb 1e-9) (> (/ (abs cr) (* la lb)) 1e-6))
      (setq res (append res (list c))))
    (setq i (1+ i)))
  (if (>= (length res) 3) res out))

(defun st-reflex (pts i / n a c b)
  (setq n (length pts))
  (setq a (nth (rem (+ i (1- n)) n) pts) c (nth i pts) b (nth (rem (1+ i) n) pts))
  (< (- (* (- (car c) (car a)) (- (cadr b) (cadr c)))
        (* (- (cadr c) (cadr a)) (- (car b) (car c)))) -1e-9))

(defun st-sisect (p1 p2 p3 p4 / d1 d2 det dx dy tt ss)
  (setq d1 (list (- (car p2) (car p1)) (- (cadr p2) (cadr p1))))
  (setq d2 (list (- (car p4) (car p3)) (- (cadr p4) (cadr p3))))
  (setq det (- (* (car d1) (cadr d2)) (* (cadr d1) (car d2))))
  (if (< (abs det) 1e-9) nil
    (progn (setq dx (- (car p3) (car p1)) dy (- (cadr p3) (cadr p1)))
      (setq tt (/ (- (* dx (cadr d2)) (* dy (car d2))) det))
      (setq ss (/ (- (* dx (cadr d1)) (* dy (car d1))) det))
      (if (and (> tt -1e-9) (< tt 1.000001) (> ss -1e-9) (< ss 1.000001))
        (list (+ (car p1) (* tt (car d1))) (+ (cadr p1) (* tt (cadr d1))) tt ss)))))

; -- διάσπαση: επιστρέφει (list poly1 poly2) ή nil --
(defun st-split (pts / n i j c aa d l dv far best h hit je p1 p2)
  (setq n (length pts) i 0 best nil)
  (while (and (< i n) (null best))
    (if (st-reflex pts i)
      (progn
        (setq c (nth i pts))
        (foreach aa (list (nth (rem (+ i (1- n)) n) pts) (nth (rem (1+ i) n) pts))
          (if (null best)
            (progn
              (setq d (list (- (car c) (car aa)) (- (cadr c) (cadr aa))))
              (setq l (sqrt (+ (* (car d) (car d)) (* (cadr d) (cadr d)))))
              (if (> l 1e-9)
                (progn
                  (setq dv (list (/ (car d) l) (/ (cadr d) l)))
                  (setq far (list (+ (car c) (* (car dv) 100000.0))
                                  (+ (cadr c) (* (cadr dv) 100000.0))))
                  (setq j 0)
                  (while (< j n)
                    (if (and (/= j i) (/= (rem (1+ j) n) i))
                      (progn
                        (setq h (st-sisect c far (nth j pts) (nth (rem (1+ j) n) pts)))
                        (if (and h (> (caddr h) 1e-6)
                                 (or (null best) (< (caddr h) (car best))))
                          (setq best (list (caddr h) (list (car h) (cadr h)) j i)))))
                    (setq j (1+ j))))))))))
    (setq i (1+ i)))
  (if best
    (progn
      (setq hit (cadr best) je (caddr best) i (nth 3 best))
      (setq p1 (st-clean (append (st-sub pts i je) (list hit))))
      (setq p2 (st-clean (append (list hit) (st-sub pts (rem (1+ je) n) i))))
      (if (and (>= (length p1) 3) (>= (length p2) 3)
               (> (abs (st-area2 p1)) 1e-6) (> (abs (st-area2 p2)) 1e-6))
        (list p1 p2)))))

; -- αναδρομική διάσπαση --
(defun st-decomp (pts dep / r)
  (if (> dep 10) (list pts)
    (progn
      (if (< (st-area2 pts) 0.0) (setq pts (reverse pts)))
      (setq pts (st-clean pts))
      (setq r (st-split pts))
      (if (null r) (list pts)
        (append (st-decomp (car r) (1+ dep)) (st-decomp (cadr r) (1+ dep)))))))

; -- λύση ορθογωνίου: 4 μαχιές + κορφιάς --
(defun st-quad (pts th / p0 p1 p2 p3 d01 d12 w m1 m2 e1 e2 e3 e4 LL u h r1 r2 lines)
  (if (/= (length pts) 4) (list nil nil)
    (progn
      (setq p0 (nth 0 pts) p1 (nth 1 pts) p2 (nth 2 pts) p3 (nth 3 pts))
      (setq d01 (distance p0 p1) d12 (distance p1 p2))
      (if (>= d01 d12)
        (progn (setq w d12 m1 (st-mid p0 p3) m2 (st-mid p1 p2))
               (setq e1 p0 e2 p3 e3 p1 e4 p2))
        (progn (setq w d01 m1 (st-mid p0 p1) m2 (st-mid p2 p3))
               (setq e1 p0 e2 p1 e3 p2 e4 p3)))
      (setq LL (distance m1 m2))
      (if (< LL 1e-9) (list nil nil)
        (progn
          (setq u (list (/ (- (car m2) (car m1)) LL) (/ (- (cadr m2) (cadr m1)) LL)))
          (setq h (/ w 2.0))
          (setq r1 (list (+ (car m1) (* (car u) h)) (+ (cadr m1) (* (cadr u) h))))
          (setq r2 (list (- (car m2) (* (car u) h)) (- (cadr m2) (* (cadr u) h))))
          (setq lines (list (list e1 r1) (list e2 r1) (list e3 r2) (list e4 r2)))
          (if (> (distance r1 r2) 1e-4)
            (setq lines (append lines (list (list r1 r2)))))
          (list lines (list (list r1 (* h th)) (list r2 (* h th)))))))))

(defun st-slope ( )
  (if (= *st-PMODE* "PCT") (/ *st-PIT* 100.0)
    (/ (sin (* *st-PIT* (/ pi 180.0))) (cos (* *st-PIT* (/ pi 180.0))))))

; -- ΚΥΡΙΑ ΕΠΙΛΥΣΗ --
(defun st-solve (poly / th orig parts allL allN res keep a b io inn dup)
  (setq th (st-slope))
  (if (< (st-area2 poly) 0.0) (setq poly (reverse poly)))
  (setq orig (st-clean poly))
  (setq parts (st-decomp poly 0))
  (setq allL (list) allN (list))
  (foreach pp parts
    (setq res (st-quad pp th))
    (if (car res) (setq allL (append allL (car res))))
    (if (cadr res) (setq allN (append allN (cadr res)))))
  ;; φίλτρο: κρατά γραμμές με άκρα σε πραγματικές κορυφές ή κόμβους
  (setq keep (list))
  (foreach ln allL
    (setq a (car ln) b (cadr ln))
    (setq io nil)
    (foreach o orig (if (< (distance a o) 1e-4) (setq io T)))
    (foreach nd allN (if (< (distance a (car nd)) 1e-3) (setq io T)))
    (setq inn nil)
    (foreach o orig (if (< (distance b o) 1e-4) (setq inn T)))
    (foreach nd allN (if (< (distance b (car nd)) 1e-3) (setq inn T)))
    (if (and io inn)
      (progn
        (setq dup nil)
        (foreach kk keep
          (if (or (and (< (distance a (car kk)) 1e-4) (< (distance b (cadr kk)) 1e-4))
                  (and (< (distance a (cadr kk)) 1e-4) (< (distance b (car kk)) 1e-4)))
            (setq dup T)))
        (if (not dup) (setq keep (append keep (list ln)))))))
  (list keep allN parts))

(defun st-prev ( / w h x0 x1 y0 y1 ym xw)
  (setq w (dimx_tile "prev") h (dimy_tile "prev"))
  (start_image "prev") (fill_image 0 0 w h 0)
  (setq x0 (fix (* w 0.12)) x1 (fix (* w 0.88)))
  (setq y0 (fix (* h 0.18)) y1 (fix (* h 0.78)))
  (setq ym (fix (/ (+ y0 y1) 2)) xw (fix (/ (- y1 y0) 2)))
  (vector_image x0 y0 x1 y0 7) (vector_image x1 y0 x1 y1 7)
  (vector_image x1 y1 x0 y1 7) (vector_image x0 y1 x0 y0 7)
  (cond
    ((= *st-TYP* "ISO")
      (vector_image x0 y0 (+ x0 xw) ym 1) (vector_image x0 y1 (+ x0 xw) ym 1)
      (vector_image x1 y0 (- x1 xw) ym 1) (vector_image x1 y1 (- x1 xw) ym 1)
      (vector_image (+ x0 xw) ym (- x1 xw) ym 1))
    ((= *st-TYP* "GAB") (vector_image x0 ym x1 ym 1))
    (T (vector_image x0 (+ y0 4) x1 (+ y0 4) 4)))
  (set_tile "sinfo" (strcat "\U+039A\U+03BB\U+03AF\U+03C3\U+03B7 "(rtos *st-PIT* 2 1)
    (if (= *st-PMODE* "PCT") "%" "\U+00B0")))
  (end_image))

(defun st-upd ( / v)
  (setq v (atof (get_tile "pit"))) (if (> v 0.0) (setq *st-PIT* v))
  (setq v (atof (get_tile "ovh"))) (if (>= v 0.0) (setq *st-OVH* v))
  (st-prev))

(defun C:STEGH ( / *error* ent pts orig dclpath dclid status f
    res lines nodes parts th ovh luk lab n0 i
    d01 d12 ra rb hh hipt bi bd pm dd eang pa pb p0 p1 nx ny el dx dy)

  (defun *error* (msg)
    (if (not (member msg (list "Function cancelled" "quit / exit abort")))
      (princ (strcat "\n" "\U+03A3\U+03C6\U+03AC\U+03BB\U+03BC\U+03B1: " msg))) (princ))

  (st-layer "STEGH-SKL" 1) (st-layer "STEGH-LUK" 4) (st-layer "STEGH-TXT" 2)
  (princ (strcat "\n" "\U+0395\U+03C0\U+03AF\U+03BB\U+03B5\U+03BE\U+03B5 \U+03BA\U+03BB\U+03B5\U+03B9\U+03C3\U+03C4\U+03AE polyline \U+03C0\U+03B5\U+03C1\U+03B9\U+03B3\U+03C1\U+03AC\U+03BC\U+03BC\U+03B1\U+03C4\U+03BF\U+03C2:"))
  (setq ent (entsel))
  (if (null ent) (exit))
  (setq pts (st-getpts (car ent)))
  (if (< (length pts) 3) (progn (princ "\n\U+03A7\U+03C1\U+03B5\U+03B9\U+03AC\U+03B6\U+03B5\U+03C4\U+03B1\U+03B9 >=3 \U+03BA\U+03BF\U+03C1\U+03C5\U+03C6\U+03AD\U+03C2.") (exit)))
  (if (< (st-area2 pts) 0.0) (setq pts (reverse pts)))
  (setq orig (st-clean pts) n0 (length orig))

  (setq dclpath (strcat (getvar "TEMPPREFIX") "stegh7.dcl"))
  (setq f (open dclpath "w"))
  (write-line "stegh7_dlg : dialog {" f)
  (write-line "  label = \"STEGH v7 \U+2014 \U+0395\U+03C0\U+03AF\U+03BB\U+03C5\U+03C3\U+03B7 \U+03A3\U+03C4\U+03AD\U+03B3\U+03B7\U+03C2 (HEXIS)\";" f)
  (write-line "  : row {" f)
  (write-line "  : column {" f)
  (write-line "    : radio_column { key = \"typ\"; label = \"\U+03A4\U+03CD\U+03C0\U+03BF\U+03C2\";" f)
  (write-line "      : radio_button { key = \"t_iso\"; label = \"\U+0399\U+03C3\U+03BF\U+03BA\U+03BB\U+03B9\U+03BD\U+03AE\U+03C2\"; value = \"1\"; }" f)
  (write-line "      : radio_button { key = \"t_gab\"; label = \"\U+0394\U+03AF\U+03C1\U+03C1\U+03B9\U+03C7\U+03C4\U+03B7\"; }" f)
  (write-line "      : radio_button { key = \"t_mon\"; label = \"\U+039C\U+03BF\U+03BD\U+03CC\U+03C1\U+03C1\U+03B9\U+03C7\U+03C4\U+03B7\"; }" f)
  (write-line "    }" f)
  (write-line "    : radio_row { key = \"pm\";" f)
  (write-line "      : radio_button { key = \"p_pct\"; label = \"%\"; value = \"1\"; }" f)
  (write-line "      : radio_button { key = \"p_deg\"; label = \"\U+039C\U+03BF\U+03AF\U+03C1\U+03B5\U+03C2\"; }" f)
  (write-line "    }" f)
  (write-line "    : edit_box { key = \"pit\"; label = \"\U+039A\U+03BB\U+03AF\U+03C3\U+03B7:\"; edit_width = 7; }" f)
  (write-line "    : edit_box { key = \"ovh\"; label = \"\U+03A0\U+03C1\U+03BF\U+03B5\U+03BE\U+03BF\U+03C7\U+03AE (m):\"; edit_width = 7; }" f)
  (write-line "    : toggle { key = \"luk\"; label = \"\U+0393\U+03B5\U+03AF\U+03C3\U+03BF (\U+03BA\U+03BB\U+03B5\U+03B9\U+03C3\U+03C4\U+03AE polyline)\"; value = \"1\"; }" f)
  (write-line "  }" f)
  (write-line "  : column {" f)
  (write-line "    : image { key = \"prev\"; width = 26; aspect_ratio = 0.7; color = 0; }" f)
  (write-line "    : text { key = \"sinfo\"; width = 28; }" f)
  (write-line "  }" f)
  (write-line "  }" f)
  (write-line "  ok_cancel;" f)
  (write-line "}" f) (close f)
  (setq dclid (load_dialog dclpath))
  (if (< dclid 0) (progn (princ "\nDCL error.") (exit)))
  (if (not (new_dialog "stegh7_dlg" dclid)) (progn (princ "\nDialog error.") (exit)))
  (set_tile "pit" (rtos *st-PIT* 2 1))
  (set_tile "ovh" (rtos *st-OVH* 2 2))
  (st-prev)
  (action_tile "t_iso" "(setq *st-TYP* \"ISO\") (st-prev)")
  (action_tile "t_gab" "(setq *st-TYP* \"GAB\") (st-prev)")
  (action_tile "t_mon" "(setq *st-TYP* \"MON\") (st-prev)")
  (action_tile "p_pct" "(setq *st-PMODE* \"PCT\") (st-upd)")
  (action_tile "p_deg" "(setq *st-PMODE* \"DEG\") (st-upd)")
  (action_tile "pit" "(st-upd)") (action_tile "ovh" "(st-upd)")
  (action_tile "accept" "(st-upd) (setq luk (get_tile \"luk\")) (done_dialog 1)")
  (action_tile "cancel" "(done_dialog 0)")
  (setq status (start_dialog)) (unload_dialog dclid)
  (if (/= status 1) (progn (princ "\n\U+0391\U+03BA\U+03CD\U+03C1\U+03C9\U+03C3\U+03B7.") (exit)))
  (setq th (st-slope) ovh *st-OVH*)
  (setq lines (list) nodes (list))

  (cond
    ((= *st-TYP* "GAB")
      (if (/= n0 4) (princ "\n\U+0394\U+03AF\U+03C1\U+03C1\U+03B9\U+03C7\U+03C4\U+03B7: \U+03B8\U+03AD\U+03BB\U+03B5\U+03B9 \U+03BF\U+03C1\U+03B8\U+03BF\U+03B3\U+03CE\U+03BD\U+03B9\U+03BF.")
        (progn
          (setq res (st-quad orig th))
          ;; μόνο ο κορφιάς (τελευταία γραμμή)
          (setq lines (list (last (car res))))
          (setq nodes (cadr res)))))

    ((= *st-TYP* "MON")
      (setq hipt (getpoint "\n\U+0394\U+03B5\U+03AF\U+03BE\U+03B5 \U+03C0\U+03C1\U+03BF\U+03C2 \U+03C4\U+03B7\U+03BD \U+03A8\U+0397\U+039B\U+0397 \U+03C0\U+03BB\U+03B5\U+03C5\U+03C1\U+03AC: "))
      (if (null hipt) (setq hipt (nth 0 orig)))
      (setq bi 0 bd nil i 0)
      (while (< i n0)
        (setq pm (st-mid (nth i orig) (nth (rem (1+ i) n0) orig)))
        (setq dd (distance (list (car hipt) (cadr hipt)) pm))
        (if (or (null bd) (< dd bd)) (progn (setq bd dd) (setq bi i)))
        (setq i (1+ i)))
      (setq pa (nth bi orig) pb (nth (rem (1+ bi) n0) orig))
      (setq eang (angle pa pb) i 0)
      (while (< i n0)
        (setq p0 (nth i orig))
        (setq dd (abs (- (* (- (car p0) (car pa)) (sin eang))
                         (* (- (cadr p0) (cadr pa)) (cos eang)))))
        (setq nodes (append nodes (list (list p0 (* dd th)))))
        (setq i (1+ i)))
      (setq lines (list (list pa pb))))

    (T
      (princ (strcat "\n" "\U+0394\U+03B9\U+03AC\U+03C3\U+03C0\U+03B1\U+03C3\U+03B7 \U+03C3\U+03B5 \U+03BF\U+03C1\U+03B8\U+03BF\U+03B3\U+03CE\U+03BD\U+03B9\U+03B1..."))
      (setq res (st-solve orig))
      (setq lines (car res) nodes (cadr res) parts (caddr res))
      (princ (strcat " " (itoa (length parts)) " \U+03C4\U+03BC\U+03AE\U+03BC\U+03B1\U+03C4\U+03B1"))))

  ;; ΣΧΕΔΙΑΣΗ
  (foreach ln lines (st-line (car ln) (cadr ln) "STEGH-SKL"))
  (st-pline orig "STEGH-SKL")
  (if (and (= luk "1") (> ovh 0.001))
    (progn
      (setq oldF (getvar "FILLETRAD") oldC (getvar "CMDECHO"))
      (setvar "CMDECHO" 0) (setvar "FILLETRAD" 0.0)
      (setq gents (list) i 0)
      (while (< i n0)
        (setq p0 (nth i orig) p1 (nth (rem (1+ i) n0) orig))
        (setq dx (- (car p1) (car p0)) dy (- (cadr p1) (cadr p0))
              el (sqrt (+ (* dx dx) (* dy dy))))
        (if (> el 1e-9)
          (progn (setq nx (/ dy el) ny (/ (- dx) el))
            (st-line (list (- (+ (car p0) (* ovh nx)) (* (/ dx el) ovh 2.0))
                           (- (+ (cadr p0) (* ovh ny)) (* (/ dy el) ovh 2.0)))
                     (list (+ (car p1) (* ovh nx) (* (/ dx el) ovh 2.0))
                           (+ (cadr p1) (* ovh ny) (* (/ dy el) ovh 2.0))) "STEGH-LUK")
            (setq gents (append gents (list (entlast))))))
        (setq i (1+ i)))
      (setq i 0)
      (while (< i (length gents))
        (setq e1 (nth i gents) e2 (nth (rem (1+ i) (length gents)) gents))
        (if (and e1 e2 (entget e1) (entget e2))
          (command "_.FILLET"
            (list e1 (st-mid (cdr (assoc 10 (entget e1))) (cdr (assoc 11 (entget e1)))))
            (list e2 (st-mid (cdr (assoc 10 (entget e2))) (cdr (assoc 11 (entget e2)))))))
        (setq i (1+ i)))
      (setvar "FILLETRAD" oldF) (setvar "CMDECHO" oldC)))

  (setq lab 0.25)
  (foreach p orig
    (st-txt (list (car p) (+ (cadr p) (* lab 0.4))) lab "+0.00" "STEGH-TXT"))
  (foreach nd nodes
    (st-txt (list (car (car nd)) (+ (cadr (car nd)) (* lab 0.4)))
      lab (strcat "+" (rtos (cadr nd) 2 2)) "STEGH-TXT"))

  (princ (strcat "\nSTEGH v7.0: " (itoa (length lines)) " \U+03B3\U+03C1\U+03B1\U+03BC\U+03BC\U+03AD\U+03C2"))
  (princ))

(princ "\nSTEGH v7.0 \U+03C6\U+03BF\U+03C1\U+03C4\U+03CE\U+03B8\U+03B7\U+03BA\U+03B5. \U+0395\U+03BD\U+03C4\U+03BF\U+03BB\U+03AE: STEGH")
(princ)
